### ISSUE TITLE
Playground "Query Variables, HTTP Headers" box 

### ISSUE THREAD

**Issue by Therapychild** [apollographql/apollo#1001]
Would it be possible to make the difference of the title in the highlighted section a little more dramatic. Overall, BEAUTIFUL design work on the playground. The ONLY thing I got stuck on was the very last step of part 4:

   " Next, paste the following into the HTTP Headers box in the bottom left:",

because for the life of me I couldn't figure out why my mutation was returning an error. It took a while, but I finally realized there are 2 tabs in the bottom left. Despite the lighter text of the selected option, it didn't stand out enough to immediately let me know that there are 2 tabs at a quick glance.

Perhaps either increasing the alpha to of the title from 0.6 to 0.8, or adding a "1px solid rgba(255, 255, 255, 0.6);"  to the active tab would be helpful. And maybe throw in a "padding-bottom: 0.1rem;" for good measure.  A very small change could make it a lot more obvious for noobs like me ;-)

By the way, 1000% awesome on the tutorial docs and playground!! 

Thank you all for your hard work, and I hope to contribute some day to this amazing project!

Jeremy,

jeremy.antoine@antoinesolutions.com

**Comment by StephenBarlow** [comment]
Thanks for the feedback and the kind words @Therapychild! The tutorial now primarily uses the Apollo Studio Explorer instead of GraphQL Playground, which should provide more contrast between these tab options. I've also updated the text of the tutorial to indicate that Headers is indeed one tab of a panel with multiple tabs.
