### ISSUE TITLE
buildSubgraphSchema errors with duplicated query type

### ISSUE THREAD

**Issue by MrDesjardins** [apollographql/apollo#1270]
**Repro**
1) Go to https://codesandbox.io/s/graphql-federation-buildsubgraphschema-version2-692el?file=/src/index.js
2) Open the Terminal from Codesandbox and execute: `node src/index.js`

**Expectation**
To merge all schema into 1 string

**Current Result**
An error saying "GraphQLSchemaValidationError: There can be only one type named "Query"."

Related Issue discussed with the graphql-tools:
https://github.com/ardatan/graphql-tools/issues/3888 

**What am I trying to accomplish (context)?**
I am migrating an existing schema to be consumed into a Federated system. I am converting the code that used `merge-graphql-schemas` to use the `buildSubgraphSchema` instead to be able to use [Federated types](https://www.apollographql.com/docs/federation/federation-spec/). My code is actually pretty close to the tutorial from that page: https://www.apollographql.com/docs/federation/subgraphs/#combined-example but it has an exception when I try to use a Federated annotation.

**Comment by StephenBarlow** [comment]
This issue is caused by the fact that the two schemas you're combining both define a `type Query`, and the single combined schema can define a single type only once. To combine multiple schemas with overlapping types like this, you need all but one definition to `extend` the type:

```graphql
type Query {
    entitya: String
}

extend type Query {
    org(orgId: Int!): Org
}
```

Hope this helps! For similar troubleshooting issues, I recommend posting in the [Apollo community forums](https://community.apollographql.com/) for a more prompt response.
